### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by xcatlkd** [xcatlkd/happygram#1]
Create authentication middleware for routing.
Include best practices;
-store hashed password
-utilize bcrypt
-

**Comment by wbobeirne** [comment]
I think this could be broken in to many smaller issues:

1) Create a user model that handles encrypting and comparing, middleware that handles user session
2) Create a Signup form and POST endpoint that creates a user
3) Create a Login form and POST endpoint that logs the user in
4) Create middleware that ensures the user is logged in for certain endpoints

**Comment by xcatlkd** [comment]
This issue will be closed. Remaining tasks will be broken out into multiple issues; as recommended.
